import { nanoid } from "nanoid";

export const dummyItems = [
  {
    id: nanoid(),
    itemId: 1,
    name: "Apple",
    quantity: 63,
    data: "",
    itemIndex: 0,
    width: 1,
    height: 1,
    weight: 0.1,
    inventoryId: "pocket",
    maxStack: 64,
  },
  {
    id: nanoid(),
    itemId: 1,
    name: "Apple",
    quantity: 1,
    data: "",
    itemIndex: 1,
    width: 1,
    height: 1,
    weight: 0.1,
    inventoryId: "pocket",
    maxStack: 64,
  },
  {
    id: nanoid(),
    itemId: 1,
    name: "Apple",
    quantity: 1,
    data: "",
    itemIndex: 4,
    width: 1,
    height: 1,
    weight: 0.1,
    inventoryId: "pocket",
    maxStack: 64,
  },
  {
    id: nanoid(),
    itemId: 2,
    name: "Gun",
    quantity: 1,
    data: "",
    itemIndex: 1,
    width: 2,
    height: 1,
    weight: 20,
    inventoryId: "backpack",
    maxStack: 64,
  },
  {
    id: nanoid(),
    itemId: 2,
    name: "Gun",
    quantity: 1,
    data: "",
    itemIndex: 1,
    width: 2,
    height: 2,
    weight: 20,
    inventoryId: "trunk",
    maxStack: 64,
  },
  {
    id: nanoid(),
    itemId: 3,
    name: "Hammer",
    quantity: 8,
    data: "",
    itemIndex: 3,
    width: 1,
    height: 1,
    weight: 1,
    inventoryId: "trunk",
    maxStack: 8,
  },
  {
    id: nanoid(),
    itemId: 3,
    name: "Hammer",
    quantity: 1,
    data: "",
    itemIndex: 0,
    width: 1,
    height: 2,
    weight: 2,
    inventoryId: "trunk",
    maxStack: 8,
  },
];
